### ISSUE TITLE
make thrax error

### ISSUE THREAD

**Issue by AlexandraToropova** [wilpert/RusPhonetizer#1]
Then I  pathed file parser.yy, i got a error.
![rvbaefh0kkw](https://cloud.githubusercontent.com/assets/17231942/20864759/8f011b1a-ba2e-11e6-80b8-6b71585f6d0d.jpg)

**Comment by wilpert** [comment]
Hi Alexandra. I am sorry you were having problems getting the software ready. It is quite a mess since my script relies on too many software packages that do not always work properly together. Add to this different compiler and OS versions and this can become a nightmare.

After several hours of testing I got it working again. Please follow these instructions:
- Download this [OpenFst version](http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.5.4.tar.gz).
- Configure it with the following parameters:` ./configure --enable-far --enable-pdt --enable-mpdt --prefix=/usr`
- Make and install it:`make; sudo make install.`
- Download this [Thrax version](http://openfst.org/twiki/pub/GRM/ThraxDownload/thrax-1.2.2.tar.gz).
- Apply the patch in RusPhonetizer/misc
- Configure it with the following parameters: ` ./configure --prefix=/usr`
- Make and install it: `make; sudo make install.`
- Compile the transduce program in RusPhonetizer/src and copy/link the compiled program under build/ to your path.
- Download [Phonetisaurus](https://www.dropbox.com/s/154q9yt3xenj2gr/phonetisaurus-0.8a.tgz) and compile it (`make `in phonetisaurus-0.8a/phonetisaurus/src/). Add the compiled binaries (phonetisaurus-0.8a/bin) to your path.
- Download the [g2p model](https://www.dropbox.com/s/hpv40je1khsz2wi/RusStressPredictor.zip?dl=0). 
- If everything was successful so far, test the main functionality running the following command in the RusPhonetizer/test: `python ../scripts/tts_transcriber.py -i rus_sentences.txt -y ../dictionaries/tts-dict-yo-list.txt  -l ../dictionaries/tts-dict-simple.pruned.txt -a ../dictionaries/tts-dict-homographs.txt -m PATH_TO_G2P_MODEL/stress_data.train.fst -g ../grammars/g2p.far`

As I mentioned in the README the phonetic transcriptions will not be as accurate as they should be if no POS prediction mechanism is used. Also, we did not have enough time to check and implement all possible lexical exceptions in Russian. Still I hope this can be helpful for you.

**Comment by wilpert** [comment]
Sorry, I closed it by mistake. Please, close the issue if you think your problem is solved.

**Comment by AlexandraToropova** [comment]
Excuse for troubling, but I can't win it. I did everything as you wrote, but on the step make Thrax i got new error.
![2016-12-05 00-04-11](https://cloud.githubusercontent.com/assets/17231942/20867824/5b98d032-ba7f-11e6-9ee4-b217ab5237fa.png)

**Comment by wilpert** [comment]
Are you using OpenFst 1.5.4? Which is your c compiler version? I have tested it with gcc version 4.8.4. Try perhaps deleting the previous OpenFst version you installed (sudo make uninstall) and reinstalling the new version (configure... make... make install).

**Comment by AlexandraToropova** [comment]
Thanks a lot for your help ! I uninstalled all packets and reinstalled them again, and it worked.

**Comment by wilpert** [comment]
Thanks for reporting back and closing the issue. I am very glad I could help.
